<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript" src="/js/bundle.js"></script>
<script type="text/javascript" src="http://code.jquery.com/qunit/qunit-1.18.0.js"></script>

<script type="text/javascript">

	QUnit.test( "hello test", function( assert ) {

		assert.ok( 1 == "1", "Passed!" );
	});
</script>