{% extends './../layouts/_default.swig' %}

{% block content %}

  <div class="maintenance-page">
    <h1>
      Undergoing Emergency Recovery
    </h1>
    <p>
      We're sorry, the Friends of Chichester Harbour database is undergoing emergency recovery procedures.
    </p>
    <p>
      We are trying to get the website fully operational as quickly as we can.
    </p>
    <p>
      Thank you for your understanding and patience.
    </p>
  </div>

{% endblock %}
